# Generated by Django 3.1.3 on 2020-12-13 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20201213_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='category',
        ),
    ]
